export const dashboardPermissionKeys = [
  "preparation",
  "administrative_requests",
  "services",
  "tasks",
  "staff_achievements",
  "supporters",
  "governance_board",
  "governance_board_members",
  "governance_general_assembly",
  "governance_general_assembly_members",
  "governance_general_assembly_minutes",
  "governance_general_assembly_membership",
  "governance_licenses",
  "governance_registration_certificate",
  "governance_donation_site_certificate",
  "governance_policies",
  "governance_committees",
  "governance_endowments",
  "logo",
  "hero",
  "donations",
  "projects",
  "giftings",
  "achievements",
  "about",
  "news",
  "gallery",
  "partners",
  "footer",
  "colors",
  "permissions",
] as const

export type DashboardPermissionKey = (typeof dashboardPermissionKeys)[number]